export const allBlogs = [
  {
    id: "1",
    title: "The Rise of Digital Art in 2025",
    author: "Sophia Turner",
    date: "Feburary 5th, 2025",
    time: "10:00 AM",
    image: "https://res.cloudinary.com/dygn4o3nv/image/upload/v1739354595/mos-design-InVeNU3UI-A-unsplash_svvjgi.jpg",
    subTitle:
      "Digital art is taking over traditional mediums. Let's explore the tools, techniques, and trends shaping the future of art.",
    content:
      "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptates dolore placeat cum, perferendis nam impedit sequi quo doloribus quisquam adipisci a libero minima architecto eum quidem laborum tempora explicabo quod nihil error ratione delectus doloremque minus fugit. Ad molestias ut qui rem eos. Vero, perspiciatis eius sapiente excepturi est odit quam at. Molestiae, qui facilis. Sed nemo qui aliquid eaque fugit dicta velit id ratione doloremque inventore, tenetur quidem beatae molestiae laboriosam. Provident, aliquid sunt autem nesciunt nobis, ut ipsam expedita eaque atque at cum, numquam error voluptate corporis ipsa repellat dolorem laborum! Eius, odit beatae excepturi iste vero tempore.",
    category: "Arts",
    tags: ["Digital Art", "NFTs", "Creativity"],
    readingTime: "6 min",
    subBlogs: [
      {
        id: "1",
        img: "https://picsum.photos/id/244/200/300",
        title: "Lorem ipsum dolor amet ilror",
        rating: "4.5",
        type: "Chair",
      },
      {
        id: "2",
        img: "https://picsum.photos/id/244/200/300",
        title: "Lorem ipsum dolor amet ilror",
        rating: "4.5",
        type: "earphones",
      },
      {
        id: "3",
        img: "https://picsum.photos/id/244/200/300",
        title: "Lorem ipsum dolor amet ilror",
        rating: "4.5",
        type: "speaker",
      },
    ],
  },
  {
    id: "2",
    title: "How AI is Revolutionizing Art and Creativity",
    author: "Liam Johnson",
    date: "January 28th, 2025",
    time: "3:15 PM",
    image: "https://res.cloudinary.com/dygn4o3nv/image/upload/v1739357829/annie-spratt-HybQKZdhZtM-unsplash_baejii.jpg",
    subTitle:
      "AI-generated art is here to stay. But is it replacing human creativity? Let's dive into this ongoing debate.",
    content:
      "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptates dolore placeat cum, perferendis nam impedit sequi quo doloribus quisquam adipisci a libero minima architecto eum quidem laborum tempora explicabo quod nihil error ratione delectus doloremque minus fugit. Ad molestias ut qui rem eos. Vero, perspiciatis eius sapiente excepturi est odit quam at. Molestiae, qui facilis. Sed nemo qui aliquid eaque fugit dicta velit id ratione doloremque inventore, tenetur quidem beatae molestiae laboriosam. Provident, aliquid sunt autem nesciunt nobis, ut ipsam expedita eaque atque at cum, numquam error voluptate corporis ipsa repellat dolorem laborum! Eius, odit beatae excepturi iste vero tempore.",
    category: "Arts",
    tags: ["AI Art", "Machine Learning", "Innovation"],
    readingTime: "7 min",
    subBlogs: [
      {
        id: "1",
        img: "https://picsum.photos/id/244/200/300",
        title: "Lorem ipsum dolor amet ilror",
        rating: "4.5",
        type: "Speaker",
      },
      {
        id: "2",
        img: "https://picsum.photos/id/244/200/300",
        title: "Lorem ipsum dolor amet ilror",
        rating: "4.5",
        type: "sneakers",
      },
      {
        id: "3",
        img: "https://picsum.photos/id/244/200/300",
        title: "Lorem ipsum dolor amet ilror",
        rating: "4.5",
        type: "sandals",
      },
    ],
  },
  {
    id: "3",
    title: "Sustainable Fashion: The Future of Clothing",
    author: "Olivia Green",
    date: "Feburary 1st, 2025",
    time: "12:30 PM",
    image: "https://res.cloudinary.com/dygn4o3nv/image/upload/v1739357835/louis-gaudiau-MFWnv4em1XA-unsplash_mp6iuc.jpg",
    subTitle:
      "Fast fashion is fading. Here's why sustainable fashion is the next big movement in the industry.",
    content:
      "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptates dolore placeat cum, perferendis nam impedit sequi quo doloribus quisquam adipisci a libero minima architecto eum quidem laborum tempora explicabo quod nihil error ratione delectus doloremque minus fugit. Ad molestias ut qui rem eos. Vero, perspiciatis eius sapiente excepturi est odit quam at. Molestiae, qui facilis. Sed nemo qui aliquid eaque fugit dicta velit id ratione doloremque inventore, tenetur quidem beatae molestiae laboriosam. Provident, aliquid sunt autem nesciunt nobis, ut ipsam expedita eaque atque at cum, numquam error voluptate corporis ipsa repellat dolorem laborum! Eius, odit beatae excepturi iste vero tempore.",
    category: "Fashion",
    tags: ["Sustainability", "Eco-Friendly", "Trends"],
    readingTime: "6 min",
    subBlogs: [
      {
        id: "1",
        img: "https://picsum.photos/id/244/200/300",
        title: "Lorem ipsum dolor amet ilror",
        rating: "4.5",
        type: "hat",
      },
      {
        id: "2",
        img: "https://picsum.photos/id/244/200/300",
        title: "Lorem ipsum dolor amet ilror",
        rating: "4.5",
        type: "mask",
      },
      {
        id: "3",
        img: "https://picsum.photos/id/244/200/300",
        title: "Lorem ipsum dolor amet ilror",
        rating: "4.5",
        type: "top",
      },
    ],
  },
  {
    id: "4",
    title: "10 Must-Visit Art Galleries Around the World",
    author: "Emma Williams",
    date: "January 22nd, 2025",
    time: "5:45 PM",
    image: "https://res.cloudinary.com/dygn4o3nv/image/upload/v1739357836/wei-mpGyJ42i3sc-unsplash_cjnjuc.jpg",
    subTitle:
      "From the Louvre to modern digital spaces, here are the top 10 art galleries every art lover should visit.",
    content:
      "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptates dolore placeat cum, perferendis nam impedit sequi quo doloribus quisquam adipisci a libero minima architecto eum quidem laborum tempora explicabo quod nihil error ratione delectus doloremque minus fugit. Ad molestias ut qui rem eos. Vero, perspiciatis eius sapiente excepturi est odit quam at. Molestiae, qui facilis. Sed nemo qui aliquid eaque fugit dicta velit id ratione doloremque inventore, tenetur quidem beatae molestiae laboriosam. Provident, aliquid sunt autem nesciunt nobis, ut ipsam expedita eaque atque at cum, numquam error voluptate corporis ipsa repellat dolorem laborum! Eius, odit beatae excepturi iste vero tempore.",
    category: "Arts",
    tags: ["Art Galleries", "Travel", "Culture"],
    readingTime: "5 min",
    subBlogs: [
      {
        id: "1",
        img: "https://picsum.photos/id/244/200/300",
        title: "Lorem ipsum dolor amet ilror",
        rating: "4.5",
        type: "skirt",
      },
      {
        id: "2",
        img: "https://picsum.photos/id/244/200/300",
        title: "Lorem ipsum dolor amet ilror",
        rating: "4.5",
        type: "dress",
      },
      {
        id: "3",
        img: "https://picsum.photos/id/244/200/300",
        title: "Lorem ipsum dolor amet ilror",
        rating: "4.5",
        type: "jewelry",
      },
    ],
  },
  {
    id: "5",
    title: "The Top 5 Fashion Trends for 2025",
    author: "Ethan Carter",
    date: "January 30th, 2025",
    time: "2:00 PM",
    image: "https://res.cloudinary.com/dygn4o3nv/image/upload/v1739357829/annie-spratt-HybQKZdhZtM-unsplash_baejii.jpg",
    subTitle:
      "From bold colors to futuristic designs, check out the hottest fashion trends for the year.",
    content:
      "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptates dolore placeat cum, perferendis nam impedit sequi quo doloribus quisquam adipisci a libero minima architecto eum quidem laborum tempora explicabo quod nihil error ratione delectus doloremque minus fugit. Ad molestias ut qui rem eos. Vero, perspiciatis eius sapiente excepturi est odit quam at. Molestiae, qui facilis. Sed nemo qui aliquid eaque fugit dicta velit id ratione doloremque inventore, tenetur quidem beatae molestiae laboriosam. Provident, aliquid sunt autem nesciunt nobis, ut ipsam expedita eaque atque at cum, numquam error voluptate corporis ipsa repellat dolorem laborum! Eius, odit beatae excepturi iste vero tempore.",
    category: "Fashion",
    tags: ["Trends", "Style", "Fashion Week"],
    readingTime: "7 min",
    subBlogs: [
      {
        id: "1",
        img: "https://picsum.photos/id/244/200/300",
        title: "Lorem ipsum dolor amet ilror",
        rating: "4.5",
        type: "jewelry",
      },
      {
        id: "2",
        img: "https://picsum.photos/id/244/200/300",
        title: "Lorem ipsum dolor amet ilror",
        rating: "4.5",
        type: "top",
      },
      {
        id: "3",
        img: "https://picsum.photos/id/244/200/300",
        title: "Lorem ipsum dolor amet ilror",
        rating: "4.5",
        type: "shorts",
      },
    ],
  },
  {
    id: "6",
    title: "Streetwear vs High Fashion: Which One is Dominating?",
    author: "Mia Anderson",
    date: "January 27th, 2025",
    time: "4:20 PM",
    image: "https://res.cloudinary.com/dygn4o3nv/image/upload/v1739354595/mos-design-InVeNU3UI-A-unsplash_svvjgi.jpg",
    subTitle:
      "Streetwear is merging with luxury brands, changing the fashion landscape forever. Which side are you on?",
    content:
      "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptates dolore placeat cum, perferendis nam impedit sequi quo doloribus quisquam adipisci a libero minima architecto eum quidem laborum tempora explicabo quod nihil error ratione delectus doloremque minus fugit. Ad molestias ut qui rem eos. Vero, perspiciatis eius sapiente excepturi est odit quam at. Molestiae, qui facilis. Sed nemo qui aliquid eaque fugit dicta velit id ratione doloremque inventore, tenetur quidem beatae molestiae laboriosam. Provident, aliquid sunt autem nesciunt nobis, ut ipsam expedita eaque atque at cum, numquam error voluptate corporis ipsa repellat dolorem laborum! Eius, odit beatae excepturi iste vero tempore.",
    category: "Fashion",
    tags: ["Streetwear", "Luxury", "Design"],
    readingTime: "5 min",
    subBlogs: [
      {
        id: "1",
        img: "https://picsum.photos/id/244/200/300",
        title: "Lorem ipsum dolor amet ilror",
        rating: "4.5",
        type: "scrunchie",
      },
      {
        id: "2",
        img: "https://picsum.photos/id/244/200/300",
        title: "Lorem ipsum dolor amet ilror",
        rating: "4.5",
        type: "dress",
      },
      {
        id: "3",
        img: "https://picsum.photos/id/244/200/300",
        title: "Lorem ipsum dolor amet ilror",
        rating: "4.5",
        type: "jewelry",
      },
    ],
  },
  {
    id: "7",
    title: "The Evolution of Football: Past, Present, and Future",
    author: "Jack Wilson",
    date: "January 29th, 2025",
    time: "11:15 AM",
    image: "https://res.cloudinary.com/dygn4o3nv/image/upload/v1739354595/mos-design-InVeNU3UI-A-unsplash_svvjgi.jpg",
    subTitle:
      "Football has changed dramatically over the decades. Let's take a look at how the sport has evolved.",
    content:
      "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptates dolore placeat cum, perferendis nam impedit sequi quo doloribus quisquam adipisci a libero minima architecto eum quidem laborum tempora explicabo quod nihil error ratione delectus doloremque minus fugit. Ad molestias ut qui rem eos. Vero, perspiciatis eius sapiente excepturi est odit quam at. Molestiae, qui facilis. Sed nemo qui aliquid eaque fugit dicta velit id ratione doloremque inventore, tenetur quidem beatae molestiae laboriosam. Provident, aliquid sunt autem nesciunt nobis, ut ipsam expedita eaque atque at cum, numquam error voluptate corporis ipsa repellat dolorem laborum! Eius, odit beatae excepturi iste vero tempore.",
    category: "Sports",
    tags: ["Football", "History", "World Cup"],
    readingTime: "7 min",
    subBlogs: [
      {
        id: "1",
        img: "https://picsum.photos/id/244/200/300",
        title: "Lorem ipsum dolor amet ilror",
        rating: "4.5",
        type: "shirt",
      },
      {
        id: "2",
        img: "https://picsum.photos/id/244/200/300",
        title: "Lorem ipsum dolor amet ilror",
        rating: "4.5",
        type: "jewelry",
      },
      {
        id: "3",
        img: "https://picsum.photos/id/244/200/300",
        title: "Lorem ipsum dolor amet ilror",
        rating: "4.5",
        type: "top",
      },
    ],
  },
  {
    id: "8",
    title: "How to Build a Timeless Wardrobe",
    author: "Noah Bennett",
    date: "January 24th, 2025",
    time: "9:30 AM",
    image: "https://res.cloudinary.com/dygn4o3nv/image/upload/v1739357836/wei-mpGyJ42i3sc-unsplash_cjnjuc.jpg",
    subTitle:
      "Fashion trends change, but style is timeless. Learn how to curate a wardrobe that lasts forever.",
    content:
      "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptates dolore placeat cum, perferendis nam impedit sequi quo doloribus quisquam adipisci a libero minima architecto eum quidem laborum tempora explicabo quod nihil error ratione delectus doloremque minus fugit. Ad molestias ut qui rem eos. Vero, perspiciatis eius sapiente excepturi est odit quam at. Molestiae, qui facilis. Sed nemo qui aliquid eaque fugit dicta velit id ratione doloremque inventore, tenetur quidem beatae molestiae laboriosam. Provident, aliquid sunt autem nesciunt nobis, ut ipsam expedita eaque atque at cum, numquam error voluptate corporis ipsa repellat dolorem laborum! Eius, odit beatae excepturi iste vero tempore.",
    category: "Fashion",
    tags: ["Minimalism", "Classic Style", "Wardrobe Essentials"],
    readingTime: "6 min",
    subBlogs: [
      {
        id: "1",
        img: "https://picsum.photos/id/244/200/300",
        title: "Lorem ipsum dolor amet ilror",
        rating: "4.5",
        type: "jewelry",
      },
      {
        id: "2",
        img: "https://picsum.photos/id/244/200/300",
        title: "Lorem ipsum dolor amet ilror",
        rating: "4.5",
        type: "[jeans]",
      },
      {
        id: "3",
        img: "https://picsum.photos/id/244/200/300",
        title: "Lorem ipsum dolor amet ilror",
        rating: "4.5",
        type: "hat",
      },
    ],
  },
  {
    id: "9",
    title: "How Sports Science is Changing Athlete Performance",
    author: "Ava Scott",
    date: "January 26th, 2025",
    time: "3:50 PM",
    image: "https://res.cloudinary.com/dygn4o3nv/image/upload/v1739357829/annie-spratt-HybQKZdhZtM-unsplash_baejii.jpg",
    subTitle:
      "From nutrition to technology, sports science is revolutionizing the way athletes train and perform.",
    content:
      "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptates dolore placeat cum, perferendis nam impedit sequi quo doloribus quisquam adipisci a libero minima architecto eum quidem laborum tempora explicabo quod nihil error ratione delectus doloremque minus fugit. Ad molestias ut qui rem eos. Vero, perspiciatis eius sapiente excepturi est odit quam at. Molestiae, qui facilis. Sed nemo qui aliquid eaque fugit dicta velit id ratione doloremque inventore, tenetur quidem beatae molestiae laboriosam. Provident, aliquid sunt autem nesciunt nobis, ut ipsam expedita eaque atque at cum, numquam error voluptate corporis ipsa repellat dolorem laborum! Eius, odit beatae excepturi iste vero tempore.",
    category: "Sports",
    tags: ["Sports Science", "Training", "Athlete Performance"],
    readingTime: "8 min",
    subBlogs: [
      {
        id: "1",
        img: "https://picsum.photos/id/244/200/300",
        title: "Lorem ipsum dolor amet ilror",
        rating: "4.5",
        type: "top",
      },
      {
        id: "2",
        img: "https://picsum.photos/id/244/200/300",
        title: "Lorem ipsum dolor amet ilror",
        rating: "4.5",
        type: "jewelry",
      },
      {
        id: "3",
        img: "https://picsum.photos/id/244/200/300",
        title: "Lorem ipsum dolor amet ilror",
        rating: "4.5",
        type: "grills",
      },
    ],
  },
  {
    id: "10",
    title: "The Best Sneakers for Performance and Style in 2025",
    author: "Benjamin Taylor",
    date: "January 20th, 2025",
    time: "7:45 PM",
    image: "https://res.cloudinary.com/dygn4o3nv/image/upload/v1739357835/louis-gaudiau-MFWnv4em1XA-unsplash_mp6iuc.jpg",
    subTitle:
      "Looking for the best sneakers for both performance and fashion? Here’s our top picks for 2025.",
    content:
      "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptates dolore placeat cum, perferendis nam impedit sequi quo doloribus quisquam adipisci a libero minima architecto eum quidem laborum tempora explicabo quod nihil error ratione delectus doloremque minus fugit. Ad molestias ut qui rem eos. Vero, perspiciatis eius sapiente excepturi est odit quam at. Molestiae, qui facilis. Sed nemo qui aliquid eaque fugit dicta velit id ratione doloremque inventore, tenetur quidem beatae molestiae laboriosam. Provident, aliquid sunt autem nesciunt nobis, ut ipsam expedita eaque atque at cum, numquam error voluptate corporis ipsa repellat dolorem laborum! Eius, odit beatae excepturi iste vero tempore.",
    category: "Sports",
    tags: ["Sneakers", "Athletic Wear", "Style"],
    readingTime: "6 min",
    subBlogs: [
      {
        id: "1",
        img: "https://picsum.photos/id/244/200/300",
        title: "Lorem ipsum dolor amet ilror",
        rating: "4.5",
        type: "grills",
      },
      {
        id: "2",
        img: "https://picsum.photos/id/244/200/300",
        title: "Lorem ipsum dolor amet ilror",
        rating: "4.5",
        type: "joggers",
      },
      {
        id: "3",
        img: "https://picsum.photos/id/244/200/300",
        title: "Lorem ipsum dolor amet ilror",
        rating: "4.5",
        type: "jewelry",
      },
    ],
  },
  {
    id: "11",
    title: "The Future of Web Development in 2025",
    author: "John Doe",
    date: "February 1st, 2025",
    time: "10:30 AM",
    image: "https://res.cloudinary.com/dygn4o3nv/image/upload/v1739357838/junel-mujar-51jzoz1dsro-unsplash_tervmb.jpg",
    subTitle:
      "Web development is evolving rapidly with new frameworks, AI integration, and enhanced performance optimizations. In this article, we explore what 2025 holds for developers.",
    content:
      "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptates dolore placeat cum, perferendis nam impedit sequi quo doloribus quisquam adipisci a libero minima architecto eum quidem laborum tempora explicabo quod nihil error ratione delectus doloremque minus fugit. Ad molestias ut qui rem eos. Vero, perspiciatis eius sapiente excepturi est odit quam at. Molestiae, qui facilis. Sed nemo qui aliquid eaque fugit dicta velit id ratione doloremque inventore, tenetur quidem beatae molestiae laboriosam. Provident, aliquid sunt autem nesciunt nobis, ut ipsam expedita eaque atque at cum, numquam error voluptate corporis ipsa repellat dolorem laborum! Eius, odit beatae excepturi iste vero tempore.",
    category: "Tech",
    tags: ["JavaScript", "AI", "React", "Future Tech"],
    readingTime: "5 min",
    isPopular: true,
    subBlogs: [
      {
        id: "1",
        img: "https://picsum.photos/id/244/200/300",
        title: "Lorem ipsum dolor amet ilror",
        rating: "4.5",
        type: "jeans",
      },
      {
        id: "2",
        img: "https://picsum.photos/id/244/200/300",
        title: "Lorem ipsum dolor amet ilror",
        rating: "4.5",
        type: "jewelry",
      },
      {
        id: "3",
        img: "https://picsum.photos/id/244/200/300",
        title: "Lorem ipsum dolor amet ilror",
        rating: "4.5",
        type: "joggers",
      },
    ],
  },
  {
    id: "12",
    title: "Mastering React Server Components",
    author: "Jane Smith",
    date: "January 28th, 2025",
    time: "3:45 PM",
    image: "https://res.cloudinary.com/dygn4o3nv/image/upload/v1739357829/annie-spratt-HybQKZdhZtM-unsplash_baejii.jpg",
    subTitle:
      "React Server Components are changing the way we build applications. Learn how to optimize performance and reduce client-side bundle sizes.",
    content:
      "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptates dolore placeat cum, perferendis nam impedit sequi quo doloribus quisquam adipisci a libero minima architecto eum quidem laborum tempora explicabo quod nihil error ratione delectus doloremque minus fugit. Ad molestias ut qui rem eos. Vero, perspiciatis eius sapiente excepturi est odit quam at. Molestiae, qui facilis. Sed nemo qui aliquid eaque fugit dicta velit id ratione doloremque inventore, tenetur quidem beatae molestiae laboriosam. Provident, aliquid sunt autem nesciunt nobis, ut ipsam expedita eaque atque at cum, numquam error voluptate corporis ipsa repellat dolorem laborum! Eius, odit beatae excepturi iste vero tempore.",
    category: "Tech",
    tags: ["React", "Next.js", "Optimization"],
    readingTime: "7 min",
    isPopular: true,
    subBlogs: [
      {
        id: "1",
        img: "https://picsum.photos/id/244/200/300",
        title: "Lorem ipsum dolor amet ilror",
        rating: "4.5",
        type: "cap",
      },
      {
        id: "2",
        img: "https://picsum.photos/id/244/200/300",
        title: "Lorem ipsum dolor amet ilror",
        rating: "4.5",
        type: "jewelry",
      },
      {
        id: "3",
        img: "https://picsum.photos/id/244/200/300",
        title: "Lorem ipsum dolor amet ilror",
        rating: "4.5",
        type: "hat",
      },
    ],
  },
  {
    id: "13",
    title: "How to Improve Web Performance with Astro",
    author: "Alice Johnson",
    date: "January 25th, 2025",
    time: "1:15 PM",
    image: "https://res.cloudinary.com/dygn4o3nv/image/upload/v1739357835/louis-gaudiau-MFWnv4em1XA-unsplash_mp6iuc.jpg",
    subTitle:
      "Astro is a powerful static site generator that helps improve web performance. Discover its benefits and how to get started.",
    content:
      "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptates dolore placeat cum, perferendis nam impedit sequi quo doloribus quisquam adipisci a libero minima architecto eum quidem laborum tempora explicabo quod nihil error ratione delectus doloremque minus fugit. Ad molestias ut qui rem eos. Vero, perspiciatis eius sapiente excepturi est odit quam at. Molestiae, qui facilis. Sed nemo qui aliquid eaque fugit dicta velit id ratione doloremque inventore, tenetur quidem beatae molestiae laboriosam. Provident, aliquid sunt autem nesciunt nobis, ut ipsam expedita eaque atque at cum, numquam error voluptate corporis ipsa repellat dolorem laborum! Eius, odit beatae excepturi iste vero tempore.",
    category: "Tech",
    tags: ["Astro", "SSG", "SEO"],
    readingTime: "6 min",
    isPopular: true,
    subBlogs: [
      {
        id: "1",
        img: "https://picsum.photos/id/244/200/300",
        title: "Lorem ipsum dolor amet ilror",
        rating: "4.5",
        type: "shorts",
      },
      {
        id: "2",
        img: "https://picsum.photos/id/244/200/300",
        title: "Lorem ipsum dolor amet ilror",
        rating: "4.5",
        type: "top",
      },
      {
        id: "3",
        img: "https://picsum.photos/id/244/200/300",
        title: "Lorem ipsum dolor amet ilror",
        rating: "4.5",
        type: "jewelry",
      },
    ],
  },
  {
    id: "14",
    title: "The Role of AI in Modern UI/UX Design",
    author: "Michael Brown",
    date: "January 20th, 2025",
    time: "9:00 AM",
    image: "https://res.cloudinary.com/dygn4o3nv/image/upload/v1739357838/junel-mujar-51jzoz1dsro-unsplash_tervmb.jpg",
    subTitle:
      "AI is transforming UI/UX design by enhancing user experiences, automating design processes, and improving accessibility.",
    content:
      "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptates dolore placeat cum, perferendis nam impedit sequi quo doloribus quisquam adipisci a libero minima architecto eum quidem laborum tempora explicabo quod nihil error ratione delectus doloremque minus fugit. Ad molestias ut qui rem eos. Vero, perspiciatis eius sapiente excepturi est odit quam at. Molestiae, qui facilis. Sed nemo qui aliquid eaque fugit dicta velit id ratione doloremque inventore, tenetur quidem beatae molestiae laboriosam. Provident, aliquid sunt autem nesciunt nobis, ut ipsam expedita eaque atque at cum, numquam error voluptate corporis ipsa repellat dolorem laborum! Eius, odit beatae excepturi iste vero tempore.",
    category: "Tech",
    tags: ["AI", "Design", "User Experience"],
    readingTime: "8 min",
    isPopular: true,
    subBlogs: [
      {
        id: "1",
        img: "https://picsum.photos/id/244/200/300",
        title: "Lorem ipsum dolor amet ilror",
        rating: "4.5",
        type: "accessories",
      },
      {
        id: "2",
        img: "https://picsum.photos/id/244/200/300",
        title: "Lorem ipsum dolor amet ilror",
        rating: "4.5",
        type: "drink",
      },
      {
        id: "3",
        img: "https://picsum.photos/id/244/200/300",
        title: "Lorem ipsum dolor amet ilror",
        rating: "4.5",
        type: "belt",
      },
    ],
  },
  {
    id: "15",
    title: "Building Scalable APIs with Node.js and Express",
    author: "Sarah Wilson",
    date: "January 18th, 2025",
    time: "4:20 PM",
    image: "https://res.cloudinary.com/dygn4o3nv/image/upload/v1739357829/annie-spratt-HybQKZdhZtM-unsplash_baejii.jpg",
    subTitle:
      "Learn how to build a scalable API using Node.js and Express, focusing on best practices, security, and performance.",
    content:
      "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptates dolore placeat cum, perferendis nam impedit sequi quo doloribus quisquam adipisci a libero minima architecto eum quidem laborum tempora explicabo quod nihil error ratione delectus doloremque minus fugit. Ad molestias ut qui rem eos. Vero, perspiciatis eius sapiente excepturi est odit quam at. Molestiae, qui facilis. Sed nemo qui aliquid eaque fugit dicta velit id ratione doloremque inventore, tenetur quidem beatae molestiae laboriosam. Provident, aliquid sunt autem nesciunt nobis, ut ipsam expedita eaque atque at cum, numquam error voluptate corporis ipsa repellat dolorem laborum! Eius, odit beatae excepturi iste vero tempore.",
    category: "Tech",
    tags: ["Node.js", "API", "Scalability"],
    readingTime: "9 min",
    isPopular: true,
    subBlogs: [
      {
        id: "1",
        img: "https://picsum.photos/id/244/200/300",
        title: "Lorem ipsum dolor amet ilror",
        rating: "4.5",
        type: "pants",
      },
      {
        id: "2",
        img: "https://picsum.photos/id/244/200/300",
        title: "Lorem ipsum dolor amet ilror",
        rating: "4.5",
        type: "belt",
      },
      {
        id: "3",
        img: "https://picsum.photos/id/244/200/300",
        title: "Lorem ipsum dolor amet ilror",
        rating: "4.5",
        type: "jewelry",
      },
    ],
  },
];
