export const artBlogs = [
    {
      id: 1,
      title: "The Rise of Digital Art in 2025",
      author: "Sophia Turner",
      date: "2025-02-05",
      time: "10:00 AM",
      image: "https://picsum.photos/id/249/200/300",
      content: "Digital art is taking over traditional mediums. Let's explore the tools, techniques, and trends shaping the future of art.",
      category: "Arts",
      tags: ["Digital Art", "NFTs", "Creativity"],
      readingTime: "6 min",
    },
    {
      id: 2,
      title: "How AI is Revolutionizing Art and Creativity",
      author: "Liam Johnson",
      date: "2025-01-28",
      time: "3:15 PM",
      image: "https://picsum.photos/id/251/200/300",
      content: "AI-generated art is here to stay. But is it replacing human creativity? Let's dive into this ongoing debate.",
      category: "Arts",
      tags: ["AI Art", "Machine Learning", "Innovation"],
      readingTime: "7 min",
    },
    {
      id: 3,
      title: "10 Must-Visit Art Galleries Around the World",
      author: "Emma Williams",
      date: "2025-01-22",
      time: "5:45 PM",
      image: "https://picsum.photos/id/252/200/300",
      content: "From the Louvre to modern digital spaces, here are the top 10 art galleries every art lover should visit.",
      category: "Arts",
      tags: ["Art Galleries", "Travel", "Culture"],
      readingTime: "5 min",
    },
];