export const fashionBlogs = [
    {
        id: "1",
        title: "Sustainable Fashion: The Future of Clothing",
        author: "Olivia Green",
        date: "2025-02-01",
        time: "12:30 PM",
        image: "https://picsum.photos/id/252/200/300",
        content: "Fast fashion is fading. Here's why sustainable fashion is the next big movement in the industry.",
        category: "Fashion",
        tags: ["Sustainability", "Eco-Friendly", "Trends"],
        readingTime: "6 min",
      },
      {
        id: "2",
        title: "The Top 5 Fashion Trends for 2025",
        author: "Ethan Carter",
        date: "2025-01-30",
        time: "2:00 PM",
        image: "https://picsum.photos/id/223/200/300",
        content: "From bold colors to futuristic designs, check out the hottest fashion trends for the year.",
        category: "Fashion",
        tags: ["Trends", "Style", "Fashion Week"],
        readingTime: "7 min",
        subBlogs: [
          {id: "1", img: "https://picsum.photos/id/244/200/300", title: "Lorem ipsum dolor amet ilror",rating: '4.5', type: "hat"},
          {id: "2", img: "https://picsum.photos/id/244/200/300", title: "Lorem ipsum dolor amet ilror",rating: '4.5', type: "jewelry"},
          {id: "3", img: "https://picsum.photos/id/244/200/300", title: "Lorem ipsum dolor amet ilror",rating: '4.5', type: "candy"},
        ],
      },
      {
        id: "3",
        title: "Streetwear vs High Fashion: Which One is Dominating?",
        author: "Mia Anderson",
        date: "2025-01-27",
        time: "4:20 PM",
        image: "https://picsum.photos/id/253/200/300",
        content: "Streetwear is merging with luxury brands, changing the fashion landscape forever. Which side are you on?",
        category: "Fashion",
        tags: ["Streetwear", "Luxury", "Design"],
        readingTime: "5 min",
        subBlogs: [
          {id: "1", img: "https://picsum.photos/id/244/200/300", title: "Lorem ipsum dolor amet ilror",rating: '4.5', type: "hat"},
          {id: "2", img: "https://picsum.photos/id/244/200/300", title: "Lorem ipsum dolor amet ilror",rating: '4.5', type: "jewelry"},
          {id: "3", img: "https://picsum.photos/id/244/200/300", title: "Lorem ipsum dolor amet ilror",rating: '4.5', type: "candy"},
        ],
      },
      {
        id: "4",
        title: "How to Build a Timeless Wardrobe",
        author: "Noah Bennett",
        date: "2025-01-24",
        time: "9:30 AM",
        image: "https://picsum.photos/id/254/200/300",
        content: "Fashion trends change, but style is timeless. Learn how to curate a wardrobe that lasts forever.",
        category: "Fashion",
        tags: ["Minimalism", "Classic Style", "Wardrobe Essentials"],
        readingTime: "6 min",
        subBlogs: [
          {id: "1", img: "https://picsum.photos/id/244/200/300", title: "Lorem ipsum dolor amet ilror",rating: '4.5', type: "hat"},
          {id: "2", img: "https://picsum.photos/id/244/200/300", title: "Lorem ipsum dolor amet ilror",rating: '4.5', type: "jewelry"},
          {id: "3", img: "https://picsum.photos/id/244/200/300", title: "Lorem ipsum dolor amet ilror",rating: '4.5', type: "candy"},
        ],
      },
]