export const sportBlogs = [
    {
        id: 1,
        title: "The Evolution of Football: Past, Present, and Future",
        author: "Jack Wilson",
        date: "2025-01-29",
        time: "11:15 AM",
        image: "https://picsum.photos/id/248/200/300",
        content: "Football has changed dramatically over the decades. Let's take a look at how the sport has evolved.",
        category: "Sports",
        tags: ["Football", "History", "World Cup"],
        readingTime: "7 min",
      },
      {
        id: 2,
        title: "How Sports Science is Changing Athlete Performance",
        author: "Ava Scott",
        date: "2025-01-26",
        time: "3:50 PM",
        image: "https://picsum.photos/id/249/200/300",
        content: "From nutrition to technology, sports science is revolutionizing the way athletes train and perform.",
        category: "Sports",
        tags: ["Sports Science", "Training", "Athlete Performance"],
        readingTime: "8 min",
      },
      {
        id: 3,
        title: "The Best Sneakers for Performance and Style in 2025",
        author: "Benjamin Taylor",
        date: "2025-01-20",
        time: "7:45 PM",
        image: "https://picsum.photos/id/250/200/300",
        content: "Looking for the best sneakers for both performance and fashion? Here’s our top picks for 2025.",
        category: "Sports",
        tags: ["Sneakers", "Athletic Wear", "Style"],
        readingTime: "6 min",
    },
]