export const techBlogs = [
    {
      id: 1,
      title: "The Future of Web Development in 2025",
      author: "John Doe",
      date: "2025-02-01",
      time: "10:30 AM",
      image: "https://picsum.photos/id/237/200/300",
      content: "Web development is evolving rapidly with new frameworks, AI integration, and enhanced performance optimizations. In this article, we explore what 2025 holds for developers.",
      category: "Tech",
      tags: ["JavaScript", "AI", "React", "Future Tech"],
      readingTime: "5 min",
      isPopular: true,
    },
    {
      id: 2,
      title: "Mastering React Server Components",
      author: "Jane Smith",
      date: "2025-01-28",
      time: "3:45 PM",
      image: "https://picsum.photos/id/238/200/300",
      content: "React Server Components are changing the way we build applications. Learn how to optimize performance and reduce client-side bundle sizes.",
      category: "Tech",
      tags: ["React", "Next.js", "Optimization"],
      readingTime: "7 min",
      isPopular: true,
    },
    {
      id: 3,
      title: "How to Improve Web Performance with Astro",
      author: "Alice Johnson",
      date: "2025-01-25",
      time: "1:15 PM",
      image: "https://picsum.photos/id/239/200/300",
      content: "Astro is a powerful static site generator that helps improve web performance. Discover its benefits and how to get started.",
      category: "Tech",
      tags: ["Astro", "SSG", "SEO"],
      readingTime: "6 min",
      isPopular: true,
    },
    {
      id: 4,
      title: "The Role of AI in Modern UI/UX Design",
      author: "Michael Brown",
      date: "2025-01-20",
      time: "9:00 AM",
      image: "https://picsum.photos/id/240/200/300",
      content: "AI is transforming UI/UX design by enhancing user experiences, automating design processes, and improving accessibility.",
      category: "Tech",
      tags: ["AI", "Design", "User Experience"],
      readingTime: "8 min",
      isPopular: true,
    },
    {
      id: 5,
      title: "Building Scalable APIs with Node.js and Express",
      author: "Sarah Wilson",
      date: "2025-01-18",
      time: "4:20 PM",
      image: "https://picsum.photos/id/241/200/300",
      content: "Learn how to build a scalable API using Node.js and Express, focusing on best practices, security, and performance.",
      category: "Tech",
      tags: ["Node.js", "API", "Scalability"],
      readingTime: "9 min",
      isPopular: true,
    },
    {
      id: 6,
      title: "Why TypeScript is Taking Over JavaScript in 2025",
      author: "Emily Carter",
      date: "2025-02-03",
      time: "11:45 AM",
      image: "https://picsum.photos/id/242/200/300",
      content: "TypeScript adoption is growing rapidly among developers. In this article, we explore its benefits, common pitfalls, and why it’s becoming the default choice for web projects.",
      category: "JavaScript",
      tags: ["TypeScript", "JavaScript", "Best Practices"],
      readingTime: "7 min",
      isPopular: false,
    },
    {
      id: 7,
      title: "CSS in 2025: Grid, Flexbox, and the Future of Styling",
      author: "Daniel White",
      date: "2025-01-31",
      time: "2:00 PM",
      image: "https://picsum.photos/id/243/200/300",
      content: "CSS continues to evolve, making styling easier and more powerful. Let’s explore new features and best practices for modern web design.",
      category: "CSS",
      tags: ["CSS", "Flexbox", "Grid", "Design"],
      readingTime: "6 min",
      isPopular: false,
    },
    {
      id: 8,
      title: "Getting Started with Rust for Web Development",
      author: "Sophia Martinez",
      date: "2025-01-29",
      time: "5:30 PM",
      image: "https://picsum.photos/id/244/200/300",
      content: "Rust is gaining traction in web development for its performance and safety. Learn how to set up your first Rust web project.",
      category: "Programming",
      tags: ["Rust", "Web Development", "Performance"],
      readingTime: "8 min",
      isPopular: false,
    },
    {
      id: 9,
      title: "Dark Mode vs Light Mode: Which One is Better for UX?",
      author: "David Kim",
      date: "2025-01-27",
      time: "9:15 AM",
      image: "https://picsum.photos/id/247/200/300",
      content: "Dark mode has become a popular design choice, but is it always the best option? Let’s analyze the pros and cons from a UX perspective.",
      category: "UI/UX",
      tags: ["Dark Mode", "Light Mode", "Design", "User Experience"],
      readingTime: "5 min",
      isPopular: false,
    },
    {
      id: 10,
      title: "How to Optimize Your Website for Core Web Vitals",
      author: "Olivia Brown",
      date: "2025-01-24",
      time: "7:00 PM",
      image: "https://picsum.photos/id/248/200/300",
      content: "Google’s Core Web Vitals impact SEO rankings significantly. Learn how to optimize your site for better performance and user experience.",
      category: "SEO",
      tags: ["SEO", "Core Web Vitals", "Performance"],
      readingTime: "7 min",
      isPopular: false,
    },
  ];
  