export const techBlogs = [
    {
      id: "1",
      title: "The Future of Web Development in 2025",
      author: "John Doe",
      date: "2025-02-01",
      time: "10:30 AM",
      image: "https://picsum.photos/id/237/200/300",
      content: "Web development is evolving rapidly with new frameworks, AI integration, and enhanced performance optimizations. In this article, we explore what 2025 holds for developers.",
      category: "Tech",
      tags: ["JavaScript", "AI", "React", "Future Tech"],
      readingTime: "5 min",
      isPopular: true,
      
    },
    {
      id: "2",
      title: "Mastering React Server Components",
      author: "Jane Smith",
      date: "2025-01-28",
      time: "3:45 PM",
      image: "https://picsum.photos/id/238/200/300",
      content: "React Server Components are changing the way we build applications. Learn how to optimize performance and reduce client-side bundle sizes.",
      category: "Tech",
      tags: ["React", "Next.js", "Optimization"],
      readingTime: "7 min",
      isPopular: true,
      
    },
    {
      id: "3",
      title: "How to Improve Web Performance with Astro",
      author: "Alice Johnson",
      date: "2025-01-25",
      time: "1:15 PM",
      image: "https://picsum.photos/id/239/200/300",
      content: "Astro is a powerful static site generator that helps improve web performance. Discover its benefits and how to get started.",
      category: "Tech",
      tags: ["Astro", "SSG", "SEO"],
      readingTime: "6 min",
      isPopular: true,
      subBlogs: [
          {id: "1", img: "https://picsum.photos/id/244/200/300", title: "Lorem ipsum dolor amet ilror",rating: '4.5', type: "hat"},
          {id: "2", img: "https://picsum.photos/id/244/200/300", title: "Lorem ipsum dolor amet ilror",rating: '4.5', type: "jewelry"},
          {id: "3", img: "https://picsum.photos/id/244/200/300", title: "Lorem ipsum dolor amet ilror",rating: '4.5', type: "candy"},
        ],
    },
    {
      id: "4",
      title: "The Role of AI in Modern UI/UX Design",
      author: "Michael Brown",
      date: "2025-01-20",
      time: "9:00 AM",
      image: "https://picsum.photos/id/240/200/300",
      content: "AI is transforming UI/UX design by enhancing user experiences, automating design processes, and improving accessibility.",
      category: "Tech",
      tags: ["AI", "Design", "User Experience"],
      readingTime: "8 min",
      isPopular: true,
      subBlogs: [
          {id: "1", img: "https://picsum.photos/id/244/200/300", title: "Lorem ipsum dolor amet ilror",rating: '4.5', type: "hat"},
          {id: "2", img: "https://picsum.photos/id/244/200/300", title: "Lorem ipsum dolor amet ilror",rating: '4.5', type: "jewelry"},
          {id: "3", img: "https://picsum.photos/id/244/200/300", title: "Lorem ipsum dolor amet ilror",rating: '4.5', type: "candy"},
        ],
    },
    {
      id: "5",
      title: "Building Scalable APIs with Node.js and Express",
      author: "Sarah Wilson",
      date: "2025-01-18",
      time: "4:20 PM",
      image: "https://picsum.photos/id/241/200/300",
      content: "Learn how to build a scalable API using Node.js and Express, focusing on best practices, security, and performance.",
      category: "Tech",
      tags: ["Node.js", "API", "Scalability"],
      readingTime: "9 min",
      isPopular: true,
      subBlogs: [
          {id: "1", img: "https://picsum.photos/id/244/200/300", title: "Lorem ipsum dolor amet ilror",rating: '4.5', type: "hat"},
          {id: "2", img: "https://picsum.photos/id/244/200/300", title: "Lorem ipsum dolor amet ilror",rating: '4.5', type: "jewelry"},
          {id: "3", img: "https://picsum.photos/id/244/200/300", title: "Lorem ipsum dolor amet ilror",rating: '4.5', type: "candy"},
        ],
    },
    
  ];
  